version: '3.8'
services:
  app:
    restart: on-failure
    build: ./
    command: uvicorn main:app --host 0.0.0.0 --port 1337 --reload
    ports:
      - "8080:1337"
    depends_on:
      - db
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: gridscaledb
    volumes:
      - ./app:/app
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: gridscaledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
